// data-testid centralizados para tests E2E.
export const SHELL = {
  app: "prisma-studio-app",
  sidebar: "sidebar",
  sidebarLogo: "sidebar-client-brand",
  sidebarFooterLogo: "sidebar-prisma-logo",
  sidebarSectionItem: (id: string) => `sidebar-section-${id}`,
  sidebarSubItem: (id: string) => `sidebar-subsection-${id}`,
  topbar: "topbar",
  topbarTitle: "topbar-title",
  topbarActions: "topbar-actions",
  themeToggle: "theme-toggle",
  notifications: "topbar-notifications",
  userAvatar: "topbar-user-avatar",
  contentTabs: "content-tabs",
};

export const HOME = {
  page: "page-inicio",
  visitorsCard: "card-visitantes",
  topPagesCard: "card-top-pages",
  quickActions: "card-quick-actions",
  quickActionItem: (id: string) => `quick-action-${id}`,
};

export const PAGES = {
  empresa: "page-empresa",
  servicios: "page-servicios",
  blog: "page-blog",
  obras: "page-obras",
  consultas: "page-consultas",
  resenas: "page-resenas",
  ajustes: "page-ajustes",
};

export const OBRAS = {
  catalogo: "obras-catalogo",
  categorias: "obras-categorias",
  materiales: "obras-materiales",
  editor: "obras-editor",
  preview: "obras-preview",
  addWorkBtn: "obras-add-work",
  searchInput: "obras-search-input",
  filterCategoryBtn: "obras-filter-category",
  filterMaterialBtn: "obras-filter-material",
  workCard: (id: string) => `work-card-${id}`,
  workEditBtn: (id: string) => `work-edit-${id}`,
  workViewBtn: (id: string) => `work-view-${id}`,
  emptyState: "obras-empty-state",
  // Editor
  editTitle: "edit-title",
  editDescription: "edit-description",
  editCategory: "edit-category",
  editMaterials: "edit-materials",
  editYear: "edit-year",
  editDimensions: "edit-dimensions",
  editStatus: "edit-status",
  editUploadImage: "edit-upload-image",
  editPublishBtn: "edit-publish-btn",
  editPreviewBtn: "edit-preview-btn",
  // Listas gestionables
  catList: "categories-list",
  catItem: (id: string) => `category-item-${id}`,
  catAdd: "category-add",
  catNewInput: "category-new-input",
  catRenameInput: (id: string) => `category-rename-${id}`,
  catToggle: (id: string) => `category-toggle-${id}`,
  catRemove: (id: string) => `category-remove-${id}`,
  matList: "materials-list",
  matItem: (id: string) => `material-item-${id}`,
  matAdd: "material-add",
  matNewInput: "material-new-input",
  matRenameInput: (id: string) => `material-rename-${id}`,
  matToggle: (id: string) => `material-toggle-${id}`,
  matRemove: (id: string) => `material-remove-${id}`,
};
