// data-testid centralizados para tests E2E.
export const SHELL = {
  app: "prisma-studio-app",
  sidebar: "sidebar",
  sidebarLogo: "sidebar-client-brand",
  sidebarFooterLogo: "sidebar-prisma-logo",
  sidebarSectionItem: (id: string) => `sidebar-section-${id}`,
  sidebarSubItem: (id: string) => `sidebar-subsection-${id}`,
  topbar: "topbar",
  topbarTitle: "topbar-title",
  topbarActions: "topbar-actions",
  themeToggle: "theme-toggle",
  notifications: "topbar-notifications",
  userAvatar: "topbar-user-avatar",
  contentTabs: "content-tabs",
};

export const HOME = {
  page: "page-inicio",
  visitorsCard: "card-visitantes",
  topPagesCard: "card-top-pages",
  quickActions: "card-quick-actions",
  quickActionItem: (id: string) => `quick-action-${id}`,
};

export const PAGES = {
  empresa: "page-empresa",
  servicios: "page-servicios",
  blog: "page-blog",
  obras: "page-obras",
  consultas: "page-consultas",
  resenas: "page-resenas",
  ajustes: "page-ajustes",
};

export const OBRAS = {
  catalogo: "obras-catalogo",
  categorias: "obras-categorias",
  materiales: "obras-materiales",
  editor: "obras-editor",
  preview: "obras-preview",
  addWorkBtn: "obras-add-work",
  searchInput: "obras-search-input",
  filterCategoryBtn: "obras-filter-category",
  filterMaterialBtn: "obras-filter-material",
  workCard: (id: string) => `work-card-${id}`,
  workEditBtn: (id: string) => `work-edit-${id}`,
  workViewBtn: (id: string) => `work-view-${id}`,
  emptyState: "obras-empty-state",
  editTitle: "edit-title",
  editDescription: "edit-description",
  editCategory: "edit-category",
  editMaterials: "edit-materials",
  editYear: "edit-year",
  editDimensions: "edit-dimensions",
  editStatus: "edit-status",
  editUploadImage: "edit-upload-image",
  editPublishBtn: "edit-publish-btn",
  editPreviewBtn: "edit-preview-btn",
  catList: "categories-list",
  catItem: (id: string) => `category-item-${id}`,
  catAdd: "category-add",
  catNewInput: "category-new-input",
  catRenameInput: (id: string) => `category-rename-${id}`,
  catToggle: (id: string) => `category-toggle-${id}`,
  catRemove: (id: string) => `category-remove-${id}`,
  matList: "materials-list",
  matItem: (id: string) => `material-item-${id}`,
  matAdd: "material-add",
  matNewInput: "material-new-input",
  matRenameInput: (id: string) => `material-rename-${id}`,
  matToggle: (id: string) => `material-toggle-${id}`,
  matRemove: (id: string) => `material-remove-${id}`,
};

export const EMPRESA = {
  page: (id: string) => `empresa-${id}`,
  preview: (id: string) => `empresa-preview-${id}`,
  saveBtn: "empresa-save",
  // Historia
  historiaTitle: "historia-title",
  historiaBody: "historia-body",
  historiaImage: "historia-image",
  historiaImageBtn: "historia-image-btn",
  historiaCtaText: "historia-cta-text",
  historiaCtaHref: "historia-cta-href",
  hitoItem: (id: string) => `hito-item-${id}`,
  hitoAdd: "hito-add",
  hitoYear: (id: string) => `hito-year-${id}`,
  hitoTitle: (id: string) => `hito-title-${id}`,
  hitoDesc: (id: string) => `hito-desc-${id}`,
  hitoRemove: (id: string) => `hito-remove-${id}`,
  // Biografia
  bioTitle: "bio-title",
  bioBody: "bio-body",
  bioPhotoBtn: "bio-photo-btn",
  // Filosofia
  filTitle: "fil-title",
  filSubtitle: "fil-subtitle",
  valorAdd: "valor-add",
  valorItem: (id: string) => `valor-item-${id}`,
  valorRemove: (id: string) => `valor-remove-${id}`,
  // Estadisticas
  estTitle: "est-title",
  estAdd: "est-add",
  estItem: (id: string) => `est-item-${id}`,
  estRemove: (id: string) => `est-remove-${id}`,
  // Proceso
  procTitle: "proc-title",
  procSubtitle: "proc-subtitle",
  procAdd: "proc-add",
  procItem: (id: string) => `proc-item-${id}`,
  procRemove: (id: string) => `proc-remove-${id}`,
  // Contacto
  contactEmail: "contact-email",
  contactPhone: "contact-phone",
  contactAddress: "contact-address",
  contactSchedule: "contact-schedule",
  contactMap: "contact-map",
  // Redes
  redItem: (id: string) => `red-item-${id}`,
  redUrl: (id: string) => `red-url-${id}`,
  redToggle: (id: string) => `red-toggle-${id}`,
  redRemove: (id: string) => `red-remove-${id}`,
  redAdd: "red-add",
};
