// data-testid centralizados para tests E2E.
export const SHELL = {
  app: "prisma-studio-app",
  sidebar: "sidebar",
  sidebarLogo: "sidebar-client-brand",
  sidebarFooterLogo: "sidebar-prisma-logo",
  sidebarSectionItem: (id: string) => `sidebar-section-${id}`,
  sidebarSubItem: (id: string) => `sidebar-subsection-${id}`,
  topbar: "topbar",
  topbarTitle: "topbar-title",
  topbarActions: "topbar-actions",
  themeToggle: "theme-toggle",
  notifications: "topbar-notifications",
  userAvatar: "topbar-user-avatar",
  contentTabs: "content-tabs",
};

export const HOME = {
  page: "page-inicio",
  visitorsCard: "card-visitantes",
  topPagesCard: "card-top-pages",
  quickActions: "card-quick-actions",
  quickActionItem: (id: string) => `quick-action-${id}`,
};

export const PAGES = {
  empresa: "page-empresa",
  servicios: "page-servicios",
  blog: "page-blog",
  obras: "page-obras",
  consultas: "page-consultas",
  resenas: "page-resenas",
  ajustes: "page-ajustes",
};

export const OBRAS = {
  catalogo: "obras-catalogo",
  categorias: "obras-categorias",
  materiales: "obras-materiales",
  editor: "obras-editor",
  preview: "obras-preview",
  addWorkBtn: "obras-add-work",
  searchInput: "obras-search-input",
  filterCategoryBtn: "obras-filter-category",
  filterMaterialBtn: "obras-filter-material",
  workCard: (id: string) => `work-card-${id}`,
  workEditBtn: (id: string) => `work-edit-${id}`,
  workViewBtn: (id: string) => `work-view-${id}`,
  emptyState: "obras-empty-state",
  editTitle: "edit-title",
  editDescription: "edit-description",
  editCategory: "edit-category",
  editMaterials: "edit-materials",
  editYear: "edit-year",
  editDimensions: "edit-dimensions",
  editStatus: "edit-status",
  editUploadImage: "edit-upload-image",
  editPublishBtn: "edit-publish-btn",
  editPreviewBtn: "edit-preview-btn",
  catList: "categories-list",
  catItem: (id: string) => `category-item-${id}`,
  catAdd: "category-add",
  catNewInput: "category-new-input",
  catRenameInput: (id: string) => `category-rename-${id}`,
  catToggle: (id: string) => `category-toggle-${id}`,
  catRemove: (id: string) => `category-remove-${id}`,
  matList: "materials-list",
  matItem: (id: string) => `material-item-${id}`,
  matAdd: "material-add",
  matNewInput: "material-new-input",
  matRenameInput: (id: string) => `material-rename-${id}`,
  matToggle: (id: string) => `material-toggle-${id}`,
  matRemove: (id: string) => `material-remove-${id}`,
};

export const EMPRESA = {
  page: (id: string) => `empresa-${id}`,
  preview: (id: string) => `empresa-preview-${id}`,
  saveBtn: "empresa-save",
  historiaTitle: "historia-title",
  historiaBody: "historia-body",
  historiaImage: "historia-image",
  historiaImageBtn: "historia-image-btn",
  historiaCtaText: "historia-cta-text",
  historiaCtaHref: "historia-cta-href",
  hitoItem: (id: string) => `hito-item-${id}`,
  hitoAdd: "hito-add",
  hitoYear: (id: string) => `hito-year-${id}`,
  hitoTitle: (id: string) => `hito-title-${id}`,
  hitoDesc: (id: string) => `hito-desc-${id}`,
  hitoRemove: (id: string) => `hito-remove-${id}`,
  // Biografia
  bioTitle: "bio-title",
  bioBody: "bio-body",
  bioPhotoBtn: "bio-photo-btn",
  // Filosofia
  filTitle: "fil-title",
  filSubtitle: "fil-subtitle",
  valorAdd: "valor-add",
  valorItem: (id: string) => `valor-item-${id}`,
  valorRemove: (id: string) => `valor-remove-${id}`,
  // Estadisticas
  estTitle: "est-title",
  estAdd: "est-add",
  estItem: (id: string) => `est-item-${id}`,
  estRemove: (id: string) => `est-remove-${id}`,
  // Proceso
  procTitle: "proc-title",
  procSubtitle: "proc-subtitle",
  procAdd: "proc-add",
  procItem: (id: string) => `proc-item-${id}`,
  procRemove: (id: string) => `proc-remove-${id}`,
  // Contacto
  contactEmail: "contact-email",
  contactPhone: "contact-phone",
  contactAddress: "contact-address",
  contactSchedule: "contact-schedule",
  contactMap: "contact-map",
  // Redes
  redItem: (id: string) => `red-item-${id}`,
  redUrl: (id: string) => `red-url-${id}`,
  redToggle: (id: string) => `red-toggle-${id}`,
  redRemove: (id: string) => `red-remove-${id}`,
  redAdd: "red-add",
};

export const SERVICIOS = {
  list: "servicios-list",
  card: (id: string) => `service-card-${id}`,
  cardEdit: (id: string) => `service-edit-${id}`,
  addBtn: "service-add",
  editor: "service-editor",
  preview: "service-preview",
  formTitle: "service-form-title",
  formShort: "service-form-short",
  formDescription: "service-form-description",
  formImage: "service-form-image",
  formImageBtn: "service-form-image-btn",
  formIcon: "service-form-icon",
  formActive: "service-form-active",
  formSave: "service-form-save",
  formDelete: "service-form-delete",
};

export const BLOG = {
  list: "blog-list",
  row: (id: string) => `article-row-${id}`,
  rowEdit: (id: string) => `article-edit-${id}`,
  rowDelete: (id: string) => `article-delete-${id}`,
  addBtn: "article-add",
  editor: "article-editor",
  preview: "article-preview",
  formTitle: "article-form-title",
  formExcerpt: "article-form-excerpt",
  formContent: "article-form-content",
  formCover: "article-form-cover",
  formCoverBtn: "article-form-cover-btn",
  formStatus: "article-form-status",
  formDate: "article-form-date",
  formPublish: "article-form-publish",
  formDraft: "article-form-draft",
  searchInput: "blog-search-input",
  filterStatus: "blog-filter-status",
};

export const CONSULTAS = {
  page: "page-consultas",
  list: "consultas-list",
  row: (id: string) => `consulta-row-${id}`,
  detail: "consulta-detail",
  searchInput: "consultas-search",
  filterBtn: "consultas-filter",
  kpi: (k: string) => `consultas-kpi-${k}`,
  replyBtn: "consulta-reply",
  pendingBtn: "consulta-mark-pending",
  archiveBtn: "consulta-archive",
  spamBtn: "consulta-mark-spam",
  removeBtn: "consulta-remove",
  backBtn: "consulta-back",
  moreActions: "consulta-more",
};

export const RESENAS = {
  page: "page-resenas",
  list: "resenas-list",
  row: (id: string) => `resena-row-${id}`,
  detail: "resena-detail",
  searchInput: "resenas-search",
  filterBtn: "resenas-filter",
  kpi: (k: string) => `resenas-kpi-${k}`,
  publishBtn: "resena-publish",
  featureBtn: "resena-feature",
  hideBtn: "resena-hide",
  removeBtn: "resena-remove",
};

export const AJUSTES = {
  page: (id: string) => `ajustes-${id}`,
  preview: "ajustes-preview",
  // Identidad
  brandName: "ajustes-brand-name",
  logoBtn: "ajustes-logo-btn",
  logoImage: "ajustes-logo-image",
  faviconBtn: "ajustes-favicon-btn",
  faviconImage: "ajustes-favicon-image",
  colorInput: "ajustes-color-input",
  colorPreset: (hex: string) => `ajustes-color-preset-${hex.replace("#", "")}`,
  fontSelect: "ajustes-font-select",
  applyBtn: "ajustes-apply",
  resetBtn: "ajustes-reset",
  // Dominio
  domainInput: "ajustes-domain",
  domainStatus: "ajustes-domain-status",
  domainSsl: "ajustes-domain-ssl",
  domainWww: "ajustes-domain-www",
  domainPublishBtn: "ajustes-domain-publish",
  // General
  generalStudio: "ajustes-general-studio",
  generalTagline: "ajustes-general-tagline",
  generalLang: "ajustes-general-lang",
  generalTz: "ajustes-general-tz",
  generalEmail: "ajustes-general-email",
  generalSave: "ajustes-general-save",
};

export const PAGINAS = {
  list: "paginas-list",
  row: (id: string) => `page-row-${id}`,
  addBtn: "page-add",
  toggleVisible: (id: string) => `page-visible-${id}`,
  remove: (id: string) => `page-remove-${id}`,
  // Editor de página
  editor: "page-editor",
  band: (id: string) => `section-band-${id}`,
  bandToggle: (id: string) => `section-toggle-${id}`,
  bandRemove: (id: string) => `section-remove-${id}`,
  bandEdit: (id: string) => `section-edit-${id}`,
  bandWidget: (id: string) => `section-widget-${id}`,
  bandBg: (id: string) => `section-bg-${id}`,
  addSectionBtn: "add-section-btn",
  catalogSearch: "catalog-search",
  catalogFilter: (cat: string) => `catalog-filter-${cat}`,
  catalogCard: (kind: string) => `catalog-card-${kind}`,
  // Editor de sección
  sectionEditor: "section-editor",
  sectionPreview: "section-preview",
  contentTitle: "content-title",
  contentSubtitle: "content-subtitle",
  contentBody: "content-body",
  contentCtaText: "content-cta-text",
  contentCtaHref: "content-cta-href",
  contentImage: "content-image",
  contentImageBtn: "content-image-btn",
};
